---
title: "Assignment 5: Analyzing repeated measures experiments"
author: "Mari Hebnes Tobekk"
format: html
editor: visual
editor_options: 
  chunk_output_type: console
---

# Lean mass

```{r}
#| echo: false
#| message: false
#| warning: false

#### GRAPHS

library(exscidata)
data("dxadata"); data("strengthvolume")

library(tidyverse)

library(tidyverse)

dxadata %>%
  select(participant:include, lean.left_leg, lean.right_leg) %>%
  pivot_longer(names_to = "leg", 
               values_to = "lean.mass", 
               cols = lean.left_leg:lean.right_leg) %>%
  mutate(leg = if_else(leg == "lean.left_leg", "L", "R"), 
         sets = if_else(multiple == leg, "multiple", "single")) %>%
  select(participant, time, sex, include, sets, leg, lean.mass) %>%
  filter(time %in% c("pre", "post")) %>%
  group_by(time, sets) %>%
  summarise(m = mean(lean.mass)) %>%
  mutate(time = factor(time, levels = c("pre", "post"))) %>%
  ggplot(aes(time, m, color = sets,
             group = sets)) + geom_line()
```

```{r}
#| echo: false
#| message: false
#| warning: false

#### BARS

dxadata %>%
  select(participant:include, lean.left_leg, lean.right_leg) %>%
  pivot_longer(names_to = "leg", 
               values_to = "lean.mass", 
               cols = lean.left_leg:lean.right_leg) %>%
  mutate(leg = if_else(leg == "lean.left_leg", "L", "R"), 
         sets = if_else(multiple == leg, "multiple", "single")) %>%
  select(participant, time, sex, include, sets, leg, lean.mass) %>%
  pivot_wider(names_from = time, 
              values_from = lean.mass) %>%
  mutate(change = post - pre) %>%
  group_by(sets) %>%
  summarise(mean_change = mean(change, na.rm = TRUE)) %>%
  ggplot(aes(sets, mean_change, fill = sets)) + 
  geom_bar(stat = "identity", width = 0.3)
```

```{r}
#| echo: false
#| message: false
#| warning: false

#### DIFFERENCE

dxadata %>%
  select(participant:include, lean.left_leg, lean.right_leg) %>%
  pivot_longer(names_to = "leg", 
               values_to = "lean.mass", 
               cols = lean.left_leg:lean.right_leg) %>%
  mutate(leg = if_else(leg == "lean.left_leg", "L", "R"), 
         sets = if_else(multiple == leg, "multiple", "single")) %>%
  select(participant, time, sex, include, sets, leg, lean.mass) %>%
  pivot_wider(names_from = time, 
              values_from = lean.mass) %>%
  mutate(change = post - pre) %>%
  group_by(sets) %>%
  summarise(mean_change = mean(change, na.rm = TRUE)) %>%
  pivot_wider(names_from = sets, 
              values_from = mean_change) %>%
  mutate(diff = multiple - single) %>%
  print()
```

```{r}
#| echo: false
#| message: false
#| warning: false

#### SUMMARY

dat <- dxadata %>%
  select(participant:include, lean.left_leg, lean.right_leg) %>%
  pivot_longer(names_to = "leg", 
               values_to = "lean.mass", 
               cols = lean.left_leg:lean.right_leg) %>%
  mutate(leg = if_else(leg == "lean.left_leg", "L", "R"), 
         sets = if_else(multiple == leg, "multiple", "single")) %>%
  select(participant, time, sex, include, sets, leg, lean.mass) %>%
  pivot_wider(names_from = time, 
              values_from = lean.mass) %>%
  mutate(change = post - pre) %>%
  print()
  
m <- lm(change ~ sets, data = dat)

summary(m)
```

```{r}
#| echo: false
#| message: false
#| warning: false

#### MEAN CHANGE

library(exscidata)
data("dxadata"); data("strengthvolume")

library(tidyverse)

library(tidyverse)

dxadata %>%
  select(participant:include, lean.left_leg, lean.right_leg) %>%
  pivot_longer(names_to = "leg", 
               values_to = "lean.mass", 
               cols = lean.left_leg:lean.right_leg) %>%
  mutate(leg = if_else(leg == "lean.left_leg", "L", "R"), 
         sets = if_else(multiple == leg, "multiple", "single")) %>%
  select(participant, time, sex, include, sets, leg, lean.mass) %>%
  pivot_wider(names_from = "time",
              values_from = "lean.mass") %>%
  mutate(change = post - pre) %>%
  group_by(sets) %>%
  summarise(mean_change = mean(change, na.rm = TRUE)) %>%
  print()
```

# Strength

```{r}
#| echo: false
#| message: false
#| warning: false

sv <- strengthvolume %>%
  filter(time %in% c("pre", "post"), 
         exercise == "legpress", 
         !is.na(load)) %>% 
  print()
```

```{r}
#| echo: false
#| message: false
#| warning: false

#### GRAF
sv %>%  
  group_by(time, sets) %>%
  summarise(m = mean(load)) %>%
  mutate(time = factor(time, levels = c("pre", "post"))) %>%
  ggplot(aes(time, m, color = sets, 
             group = sets)) + geom_line()
```

```{r}
#| echo: false
#| message: false
#| warning: false

#### BARS
sv %>%
  pivot_wider(names_from = time, 
              values_from = load) %>%
  mutate(change = post - pre) %>%
  group_by(sets) %>%
  summarise(mean_change = mean(change, na.rm = TRUE)) %>%
  ggplot(aes(sets, mean_change, fill = sets)) + 
  geom_bar(stat = "identity", width = 0.3)
  
```

```{r}
#| echo: false
#| message: false
#| warning: false


#### DIFFERANSE
sv %>%
  pivot_wider(names_from = time, 
              values_from = load) %>%
  mutate(change = post - pre) %>%
  group_by(sets) %>%
  summarise(mean_change = mean(change, na.rm = TRUE)) %>%
  pivot_wider(names_from = sets, 
              values_from = mean_change) %>%
  mutate(diff = multiple - single) %>%
  print()
```

```{r}
#| echo: false
#| message: false
#| warning: false

#### REGRESJON
calc <- sv %>%
  pivot_wider(names_from = time, 
              values_from = load) %>%
  mutate(change = post - pre) %>%
  print()

m1 <- lm(change ~ sets, data = calc)
summary(m1)
```
